import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/Header";
import { init } from "./prepaintClassSetter";
import { Button } from "@/components/Buttom/Button";
import { FC } from "react";
import SideMenu from "@/components/SideMenu/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: init,
          }}
        />
      </head>
      <Providers>
        <body className="bg-orange-50 dark:bg-slate-900 min-h-screen text-slate-900 dark:text-slate-50 relative">
          <Header />
          <div className="flex flex-row">
            <SideMenu />
            <main className="flex-1">{children}</main>
          </div>
        </body>
      </Providers>
    </html>
  );
}
